
apiVersion: apps/v1
kind: Deployment
metadata:
  name: academic-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academic-api
  template:
    metadata:
      labels:
        app: academic-api
    spec:
      containers:
      - name: academic-api
        image: academic-api:latest
        ports:
        - containerPort: 8000
